name: Workflow 1

on: push

jobs:
  create-draft-release:
    name: Save artifact
    runs-on: ubuntu-latest
    steps:
      - name: Save artifact
        run: echo "some artifact" > .artifact
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: Artifact
          path: .artifact
          retention-days: 1
